stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile/Dockerfile
      buildContext: .
      tag: myweb-1:${CICD_EXECUTION_SEQUENCE}
    env:
      PLUGIN_DEBUG: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./yaml/k8s-myweb.yaml
timeout: 60
