stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./dockerfile/
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}/${CICD_GIT_REPO_NAME}:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: harbor.yuandingit.com
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./yaml/k8s-myweb.yaml
timeout: 60
