apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      run: myweb
  template:
    metadata:
      labels:
        run: myweb
    spec:
      containers:
      - image: docker-registry.p-k2jbx-pipeline/myweb-2:latest
        name: myweb
---
apiVersion: v1
kind: Service
metadata:
  name: myweb-svc
spec:
  selector:
    run: myweb
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort

